import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import MobileNav from "@/components/MobileNav/MobileNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full flex flex-col bg-neutral-50`}
      >
       <div className="w-full flex justify-center border-b border-[#F5F5F5]"><Navbar/></div> 
       <main className="w-full flex justify-center">
       <div className="items-center justify-items-center w-[80%] max-md:w-[90%]">
        {children}
       </div>
        </main> 
        <div className="w-full fixed bottom-0 flex justify-center border-b border-[#F5F5F5] bg-white md:!hidden"> <MobileNav/></div>
      </body>
    </html>
  );
}
